FROM openjdk:11.0.5-jdk

WORKDIR /code
COPY *.gradle gradle.* gradlew ./
COPY gradle ./gradle
RUN ./gradlew -q --no-daemon build || return 0

COPY src/ src/

RUN ["./gradlew", "-q", "--no-daemon", "shadowJar"]

