version: "3.7"
services:
  mongo:
    build:
      context: ../mongodb
    expose:
      - 27017
    networks:
      - service
    volumes:
      - mongo-drive:/data/db

  app:
    build:
      context: ../friends-service
      dockerfile: Dockerfile.multi
    command: ["/scripts/startup.sh"]
    depends_on:
      - mongo
    expose:
      - 8080
    networks:
      - frontend
      - service
    volumes:
      - ./friends-service/scripts:/scripts

  nginx:
    depends_on:
      - app
    image: nginx:1.19.6-alpine
    ports:
      - ${PORT}:8080
    networks:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  service:
  frontend:

volumes:
  mongo-drive:
